#!/bin/bash

## Open Applications
FILE="$HOME/.cache/eww_launch.xyz"
EWW="$HOME/.local/bin/eww -c $HOME/.config/eww"
cmd="xdg-open"

if [[ "$1" == "--firefox" ]]; then
	${EWW} close-all && rm -rf "$FILE" && firefox &

elif [[ "$1" == "--whatsapp" ]]; then
	${EWW} close-all && rm -rf "$FILE" && firefox "https://web.whatsapp.com" &

elif [[ "$1" == "--github" ]]; then
	${EWW} close-all && rm -rf "$FILE" && firefox "https://github.com" &

elif [[ "$1" == "--reddit" ]]; then
	${EWW} close-all && rm -rf "$FILE" && firefox "https://reddit.com" &

elif [[ "$1" == "--code" ]]; then
	${EWW} close-all && rm -rf "$FILE" && code &

elif [[ "$1" == "--discord" ]]; then
	${EWW} close-all && rm -rf "$FILE" && discord &

elif [[ "$1" == "--spotify" ]]; then
	${EWW} close-all && rm -rf "$FILE" && spotify &
fi
